
services:
  - type: web
    name: ptv-trmnl-new
    env: node
    plan: free
    buildCommand: npm ci
    startCommand: node server.js
    envVars:
      - key: ODATA_KEY
        sync: false
      # Optional
      - key: WEATHER_KEY
        sync: false
